dist: xenial
language: node_js
cache: npm
branches:
    only:
        - master

node_js:
    - "node"

before_script:
    - cd ./nodejs

script:
    - npm install
    - npm run postinstall

after_script:
    - npm run build
    - npm run test
